version: '3.9'

services:
  soraya-management:
    container_name: soraya-management
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mssql-database

  mssql-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: mssql-database
    volumes:
      - dev-db-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testing123!
    ports:
      - "1433:1433"

volumes:
  dev-db-data:
